# Generated by Django 4.0.4 on 2022-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_venue_match_player2_match_player3_match_team1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ManyToManyField(to='matches.matchplayer'),
        ),
    ]
