# Generated by Django 4.0.4 on 2022-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchplayer_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.AddField(
            model_name='match',
            name='batter',
            field=models.ManyToManyField(related_name='batter_scores', to='matches.matchplayer'),
        ),
    ]
