# Generated by Django 4.0.4 on 2022-05-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_match_player1_match_batter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
