# Generated by Django 4.0.4 on 2022-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchplayer',
            old_name='balls',
            new_name='no_balls',
        ),
        migrations.AddField(
            model_name='match',
            name='bowler',
            field=models.ManyToManyField(related_name='bowler_scores', to='matches.matchplayer'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='balls_faced',
            field=models.IntegerField(default=0, verbose_name='b/f'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='overs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='wides',
            field=models.IntegerField(default=0),
        ),
    ]
