# Generated by Django 4.0.4 on 2022-05-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('matches', '0007_rename_balls_matchplayer_no_balls_match_bowler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0, verbose_name='b/f')),
                ('batter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('how_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.howout')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='batter',
        ),
        migrations.RemoveField(
            model_name='match',
            name='bowler',
        ),
        migrations.DeleteModel(
            name='MatchPlayer',
        ),
        migrations.AddField(
            model_name='matchbatter',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
    ]
